export interface IConsumeListItem {
  createTime: string;
  updateTime: string;
  totalAmount: number;
  repastPrice: number;
  repastIntro: string;
  transferAccounts: number;
  transferIntro: string;
  snacksPrice: number;
  snacksIntro: string;
  vehiclePrice: number;
  vehicleIntro: string;
  lifePrice: number;
  lifeIntro: string;
  tripPrice: number;
  tripIntro: string;
  shoppingPrice: number;
  shoppingIntro: string;
  otherPrice: number;
  otherIntro: string;
  drinksPrice: number;
  drinksIntro: string | null;
  cosmeticPrice: number;
  cosmeticIntro: string | null;
  _id?: string;
  id: number;
}

export const list: IConsumeListItem[] = [
  {
    id: 191,
    createTime: '2020-01-03 16:43:17',
    repastPrice: 50,
    repastIntro: '["早餐10","午餐20","晚餐20"]',
    vehiclePrice: 12,
    vehicleIntro: '["地铁两次，每次6元"]',
    drinksPrice: 0,
    drinksIntro: null,
    snacksPrice: 0,
    snacksIntro: '',
    transferAccounts: 0,
    transferIntro: '',
    lifePrice: 0,
    lifeIntro: '',
    cosmeticPrice: 0,
    cosmeticIntro: '',
    otherPrice: 0,
    otherIntro: '',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 62,
    tripPrice: 0,
    tripIntro: '',
    shoppingPrice: 0,
    shoppingIntro: '',
  },
  {
    id: 91,
    createTime: '2019-09-23 00:02:16',
    repastPrice: 13,
    repastIntro: '["体验：13元"]',
    vehiclePrice: 14,
    vehicleIntro: '["体验：14元"]',
    drinksPrice: 0,
    drinksIntro: null,
    snacksPrice: 11,
    snacksIntro: '["体验：11元"]',
    transferAccounts: 8,
    transferIntro: '["体验：8元"]',
    lifePrice: 2,
    lifeIntro: '["体验：2元"]',
    cosmeticPrice: 3,
    cosmeticIntro: '["体验：3元"]',
    otherPrice: 16,
    otherIntro: '["体验：16元"]',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 80,
    tripPrice: 7,
    tripIntro: '["体验：7元"]',
    shoppingPrice: 6,
    shoppingIntro: '["体验：6元"]',
  },
  {
    id: 90,
    createTime: '2019-09-17 23:52:24',
    repastPrice: 5,
    repastIntro: '',
    vehiclePrice: 5,
    vehicleIntro: '',
    drinksPrice: 0,
    drinksIntro: null,
    snacksPrice: 5,
    snacksIntro: '',
    transferAccounts: 5,
    transferIntro: '',
    lifePrice: 5,
    lifeIntro: '',
    cosmeticPrice: 5,
    cosmeticIntro: '',
    otherPrice: 5,
    otherIntro: '',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 45,
    tripPrice: 5,
    tripIntro: '',
    shoppingPrice: 5,
    shoppingIntro: '',
  },
  {
    id: 89,
    createTime: '2019-09-09 23:52:24',
    repastPrice: 20,
    repastIntro: '',
    vehiclePrice: 20,
    vehicleIntro: '',
    drinksPrice: 0,
    drinksIntro: 'null',
    snacksPrice: 20,
    snacksIntro: '',
    transferAccounts: 20,
    transferIntro: '',
    lifePrice: 20,
    lifeIntro: '',
    cosmeticPrice: 0,
    cosmeticIntro: '',
    otherPrice: 0,
    otherIntro: '',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 100,
    tripPrice: 0,
    tripIntro: '',
    shoppingPrice: 0,
    shoppingIntro: '',
  },
  {
    id: 88,
    createTime: '2019-08-28 23:52:24',
    repastPrice: 14,
    repastIntro: '["体验：14元"]',
    vehiclePrice: 23,
    vehicleIntro: '["体验：23元"]',
    drinksPrice: 0,
    drinksIntro: null,
    snacksPrice: 6,
    snacksIntro: '["体验：6元"]',
    transferAccounts: 65,
    transferIntro: '["体验：65元"]',
    lifePrice: 32,
    lifeIntro: '["体验：32元"]',
    cosmeticPrice: 0,
    cosmeticIntro: '',
    otherPrice: 0,
    otherIntro: '',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 140,
    tripPrice: 0,
    tripIntro: '',
    shoppingPrice: 0,
    shoppingIntro: '',
  },
  {
    id: 87,
    createTime: '2019-08-17 23:52:24',
    repastPrice: 10,
    repastIntro: '["体验消费：10元","体验消费：10元"]',
    vehiclePrice: 10,
    vehicleIntro: '["体验消费：10元","体验消费：10元"]',
    drinksPrice: 0,
    drinksIntro: null,
    snacksPrice: 10,
    snacksIntro: '["体验消费：10元","体验消费：10元"]',
    transferAccounts: 10,
    transferIntro: '["体验消费：10元"]',
    lifePrice: 10,
    lifeIntro: '["体验消费：10元"]',
    cosmeticPrice: 10,
    cosmeticIntro: '["体验消费：10元"]',
    otherPrice: 10,
    otherIntro: '["体验消费：10元"]',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 90,
    tripPrice: 10,
    tripIntro: '["体验消费：10元"]',
    shoppingPrice: 10,
    shoppingIntro: '["体验消费：10元"]',
  },
  {
    id: 30,
    createTime: '2019-08-02 17:55:15',
    repastPrice: 1,
    repastIntro: '',
    vehiclePrice: 0,
    vehicleIntro: '',
    drinksPrice: 0,
    drinksIntro: null,
    snacksPrice: 0,
    snacksIntro: '',
    transferAccounts: 0,
    transferIntro: '',
    lifePrice: 0,
    lifeIntro: '',
    cosmeticPrice: 0,
    cosmeticIntro: '',
    otherPrice: 0,
    otherIntro: '',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 1,
    tripPrice: 0,
    tripIntro: '',
    shoppingPrice: 0,
    shoppingIntro: '',
  },
  {
    id: 10,
    createTime: '2019-07-13 22:26:16',
    repastPrice: 23,
    repastIntro: '',
    vehiclePrice: 23,
    vehicleIntro: '',
    drinksPrice: 0,
    drinksIntro: null,
    snacksPrice: 23,
    snacksIntro: '',
    transferAccounts: 23,
    transferIntro: '',
    lifePrice: 23,
    lifeIntro: '',
    cosmeticPrice: 23,
    cosmeticIntro: '',
    otherPrice: 23,
    otherIntro: '',
    updateTime: '2020-05-24 13:55:14',
    totalAmount: 207,
    tripPrice: 23,
    tripIntro: '',
    shoppingPrice: 23,
    shoppingIntro: '',
  },
];

